version: '3'
services:

  nginx:
    build: ./stack/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_DOMAIN=courses.localhost
      - APP_CDN_DOMAIN=courses-2daa.kxcdn.com
    tmpfs:
      - /tmp
      - /var/ngx_pagespeed_cache
    links:
      - varnish:varnish
      - memcached:memcached
    depends_on:
      - varnish
      - memcached

  varnish:
    build:
      context: ./stack/varnish
    restart: always
    links:
      - app:app
    depends_on:
      - app

  app:
    build: ./stack/app.development
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=courses.localhost
      - APP_STAGE=development
      - APP_MODE=dev
      - APP_UNATTENDED_UPGRADE=true
      - APP_INSTALL_SAMPLE_DATA=true
      - APP_CRON=true
      - APP_WP_DB_HOST=db
      - APP_WP_DB_NAME=app
      - APP_WP_DB_PREFIX=wp_
      - APP_WP_DB_USER=root
      - APP_WP_DB_PASSWORD=secret
      - APP_WP_ENV=development
      - APP_WP_HOME=https://courses.localhost
      - APP_WP_SITEURL=https://courses.localhost/wp
      - APP_WP_DISABLE_WP_CRON=true
      - 'APP_WP_AUTH_KEY="_hze=m:Vjonnmhrxy/}C*!$$m./GYi$$9QV+pZ}[`)I@l+f.y6AZip*m>TMeci&I('
      - 'APP_WP_SECURE_AUTH_KEY=">h>bcm-Z[oj4!}RV].1XaSo4K9_9#d9X^)Z(SJ/Eeg|6I![qB*Ds_ndlL@61R6{>"'
      - 'APP_WP_LOGGED_IN_KEY="1?S1G&SsabFpssGUrT-?9j%P#;#_;Nt#=`.N>JFW_Mb}7K<nXjmZ0%OFHX])0mjX"'
      - 'APP_WP_NONCE_KEY="{2f!&XepF,1mdM*}V8U@VY[,Wm>;]Iu]>eva&X>k6KWIdd@icJySfyNSRkLMB4;S"'
      - 'APP_WP_AUTH_SALT="<RN.&jd{[6kn&A^fcnD[AGh`9^-}qbkB&{DIC?ciL0,m$$n5CP9f+)w4H1`{o3Ns9"'
      - 'APP_WP_SECURE_AUTH_SALT="X_6Iiv_)RRv<K?m,H$$rdtq^1@-M!K5UIDCIc:WUP1esxWGbDsH)zC+33[Bp`o0tC"'
      - 'APP_WP_LOGGED_IN_SALT="=!c+g<ckbNrgoY0}zFA9qw!.Zk$$djE*^Cq_,eo4<q[m#H1g%Pnmuk[nc[+UNSwL0"'
      - 'APP_WP_NONCE_SALT="99M+xc]fpn;}7_Z@MnD>;83#o%|1{wyb_}a@bl?*+V{7]QlY8s_#@Rh=9,aZK@`Q"'
    ports:
      - "8090:80"
    tmpfs:
      - /tmp
    volumes:
      - courses-app:/app:nocopy
    links:
      - rabbitmq:rabbitmq
      - redis:redis
      - es:es
      - db:db
    depends_on:
      - rabbitmq
      - redis
      - es
      - db

  phpmyadmin:
    build:
      context: ./stack/phpmyadmin
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - "8080:80"
    links:
      - db:db
    depends_on:
      - db

  automysqlbackup:
    build:
      context: ./stack/automysqlbackup
    restart: always
    environment:
      - USERNAME=root
      - PASSWORD=secret
      - DBHOST=db
      - DBNAMES=app
      - DBEXCLUDE="performance_schema information_schema"
      - CRON_SCHEDULE="0 23 * * *"
      - LATEST="yes"
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - automysqlbackup-data:/backup

  rabbitmq:
    build:
      context: ./stack/rabbitmq
    ports:
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    build:
      context: ./stack/redis
    restart: always

  memcached:
    build:
      context: ./stack/memcached
    restart: always

  es:
    build:
      context: ./stack/es
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  db:
    build:
      context: ./stack/db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    volumes:
      - db-data:/var/lib/mysql

  borg:
    build:
      context: ./stack/borg
    restart: always
    environment:
      BORGBACKUP_CLIENT_HOSTNAME: 'courses.development'
      BORGBACKUP_PASSPHRASE: 'Dhl9EiNohr5koosh1Wohs3Shoo3ooZ6p'
      BORGBACKUP_RSA_PRIVATE: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEAzHdSfeOU3YPAxJE25KDM/8PyK2tDNZSHSWslSIm9daYUXHZV
        EaLaJAtrvExfMWUe6JquBLhm/GXkx1Xr4q80JuuvCPKW215L7mgblpWgRQdr17H1
        dUVcrhhZMKgA4MGiKfnZ2Gneq/bSdjtKnD1L3nebO3oIxzcnfsrPjwr7cuhYNz9K
        urAwQdArNDX0U6y7uCWiOnWy5g6pnoORzGFUcCb5IQXA5vpZ1wAVJtNwd2OsYynn
        9h9AXdDRh6NuDnHgJHWaSiyxEJB4cEYlfrHCsMvKbrnjCELUI97f8MCNNBKzZLiw
        7EpJ/ZdT2dRJk1b39PgUVrFMVFimtjiJZIWDJwIDAQABAoIBAQDCyQHbUE3nYbbp
        DHZBBDeHiUJRvtO+XYsslFhmbGIDjH5lP433SS+Lmx29uvwM8IqriYAymwHxfZif
        leksgUCru2d6nLC+t2ya6K8vm8edO16vk6eFWtjaOfPt+H8tnwo/9vhjxSgOpwsE
        +6MuiO6YN1W5KZ7nOlHz5n4phYragW5qIR89xQvSpQrCxCpP4oRF+nZ8DnvAKlac
        scgcdkJsbwbsIPAw2qfk5+xGhr3GlpMn3pOFw7shCKRZMfR0i8PN3mjX77pIK5eq
        7tp7LT+0C2qslHrx4NwefIx5bZmLFIkTK7p442/Qql1yLqpXhYQEb6e/l40wm5Wd
        du/OyfNxAoGBAObaCc9DNu4RNuln/8Vf98aVxO9DdMgi8jObdj6b0jUUBR7wtY+E
        chFFZ0u/Tjy1JJgu75vA9+1Q4bT59M7ZtdqmtE84jHQVayGyKBIoRxukSDqKMwIT
        Gr3qaetusVFSlqFQaL1KvXS1e70NJKNtko6OWbP1QLd4otaeTwYTvKd9AoGBAOK9
        chAqZPz6P9TNs0vkU8VY1dXdX19+8mm7NnCUcQwLZArfDbFETzhfzZxMhQMn/ZTQ
        KhRLTGd1deiHdOHqkzJ3FC6+Ct7YmNRTTT+FyOQSqOnDg7UAKaUbcqnGiOL/z3RM
        wyoKNyyienIVPKYlki0mmwvX1efXDqhsKdmg7j5zAoGAHWxS7cDSYnt9NTiVJ/H4
        Ya47IIfHfa6+kgdRhd9UZoF7uZrSeU1XQI5JASWL8j7gQClTTtXEg9HYQrnNEwQ6
        oni26JX7iNwmAHB1nQLXNVW2AwgUQkJvGR+kimZcYVIWcs8N2nqJNTPgZpMjRVU0
        5ciM9Fvg+MF+d75LsimX1P0CgYEAmKLbpFJFxZ9ZVRJcftxoIFPbL6tkxs6YteCX
        l1X2fBs277KUbx8DDXpA2dURPbywEnvHt/2wo30JMM3vOx5ElRZgec7pVncM+vJQ
        8FBJmm+NUkCR60j+v+0oVW4XPGjk6O+7+hMCbYO7Vg1B1L86FjcE7QYRM48siOi3
        i4+wkk0CgYEAjs+FlOFHN/U7cqLq36vFM29ORfamjS7A0wTjpmze01zC/U45yZsB
        gt+ucLUjlQ2Ems0b4WLwfM/r7cUOhDm7GqKeo2prh58gGgBQirbVdmypzeHmifzP
        YV8zGExKV0NjfS4MCVJ6aRiDsKGmpjGtfwfw9FMwvJ500B+ySkzGx+4=
        -----END RSA PRIVATE KEY-----
      BORGBACKUP_RSA_PUBLIC: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMd1J945Tdg8DEkTbkoMz/w/Ira0M1lIdJayVIib11phRcdlURotokC2u8TF8xZR7omq4EuGb8ZeTHVevirzQm668I8pbbXkvuaBuWlaBFB2vXsfV1RVyuGFkwqADgwaIp+dnYad6r9tJ2O0qcPUved5s7egjHNyd+ys+PCvty6Fg3P0q6sDBB0Cs0NfRTrLu4JaI6dbLmDqmeg5HMYVRwJvkhBcDm+lnXABUm03B3Y6xjKef2H0Bd0NGHo24OceAkdZpKLLEQkHhwRiV+scKwy8puueMIQtQj3t/wwI00ErNkuLDsSkn9l1PZ1EmTVvf0+BRWsUxUWKa2OIlkhYMn root@courses
    volumes:
      - automysqlbackup-data:/var/borg/automysqlbackup-data
      - courses-app:/var/borg/app-app

  app_infra_up:
    image: dadarek/wait-for-dependencies
    environment:
      SLEEP_LENGTH: 1
      TIMEOUT_LENGTH: 300
    links:
      - rabbitmq:rabbitmq
      - redis:redis
      - es:es
      - db:db
    depends_on:
      - rabbitmq
      - redis
      - es
      - db
    command: rabbitmq:5672 redis:6379 es:9200 db:3306

  app_wait_for:
    image: dadarek/wait-for-dependencies
    environment:
      SLEEP_LENGTH: 1
      TIMEOUT_LENGTH: 300
    links:
      - app:app
    depends_on:
      - app
    command: app:80

volumes:
  courses-app:
    external: true
  rabbitmq-data:
    external: false
  es-data:
    external: false
  db-data:
    external: false
  automysqlbackup-data:
    external: false
