---
- hosts: all

  connection: local

  tasks:
    - name: Add mappings to /etc/hosts
      tags:
        - hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} courses {{ item.name }}"
      with_items:
        - { name: courses.localhost, ip: 127.0.0.1 }
        - { name: courses.max.local, ip: 12.0.0.201 }
