---

- name: Push docker-compose.yml
  become: yes
  become_user:  '{{ app.user.name }}'
  copy:
    src: docker-compose.yaml
    dest: ~/docker-compose.yaml

- name: Stack pull!
  become: yes
  become_user: '{{ app.user.name }}'
  shell: cd ~/ && make stack-pull

- name: Stack down!
  become: yes
  become_user: '{{ app.user.name }}'
  shell: cd ~/ && make stack-down

- name: Stack up!
  become: yes
  become_user: '{{ app.user.name }}'
  shell: cd ~/ && make stack-up
