---

- name: Set max shared memory map count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present

- name: Allow access from trusted ips
  ufw:
    direction: in
    port: '9200'
    src: '{{ item }}'
    proto: tcp
    rule: allow
    state: enabled
  with_items: '{{ trusted_ips}}'
